### ISSUE TITLE
`Workflow`: Deploy File to VM

### ISSUE THREAD

**Issue by Mtze** [ls1intum/.github#2]
Similar to 

```yml
      - name: Copy master.cf to VM Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          source: "fu"
          target: "/bar"
```

With sane defaults (e.g. proxy config for our org)
