### ISSUE TITLE
`Workflow`: Docker compose down 

### ISSUE THREAD

**Issue by Mtze** [ls1intum/.github#4]
Something like this: 
```yml
steps:
      - name: SSH to VM and Execute Docker-Compose Down
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          script: |
            docker compose -f docker-compose.prod.yml --env-file=.env.prod down --remove-orphans --rmi all
```
Inputs
- Path to compose file 
- optional path to env file 
- Host

Important: This command must not cancel the build if it fails
